name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu20.04

    steps:
    - uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    -
        name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
    -
      name: Build and push
      uses: docker/build-push-action@v3
      with:
        push: true
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKER_REGISTRY }}:${{ secrets.DOCKER_TAG }}      
      
    - name: Create .env file
      run: |
        jq -r 'to_entries|map("\(.key)=\(.value|tostring)")|.[]' <<< "$FAST_ENV" > .env
      env:
        FAST_ENV: ${{ toJson(secrets) }}
        
  deploy_to_ec2:
    name: deploy env file and FastAPI
    needs: [ "build" ]
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        
      - name: Commit and push changes
        uses: devops-infra/action-commit-push@v0.3
        with:
          github_token: ${{ secrets.GIT_ACCESS_TOKEN }}
          commit_message: Image version updated
          
      - name: deploy with AWS codeDeploy
        run: aws deploy create-deployment
          --application-name numanguan
          --deployment-config-name CodeDeployDefault.OneAtATime
          --deployment-group-name numanguan_deploy_group
  
